// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PracticeformTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void practiceform() {
    driver.get("http://www.practiceselenium.com/practice-form.html");
    driver.manage().window().setSize(new Dimension(1362, 694));
    driver.findElement(By.name("firstname")).click();
    driver.findElement(By.name("firstname")).sendKeys("Huong");
    driver.findElement(By.name("lastname")).click();
    driver.findElement(By.name("lastname")).sendKeys("Nguyen Thi");
    driver.findElement(By.id("sex-1")).click();
    driver.findElement(By.id("exp-6")).click();
    driver.findElement(By.id("tea1")).click();
    driver.findElement(By.id("tea2")).click();
    driver.findElement(By.id("tool-0")).click();
    driver.findElement(By.id("tool-1")).click();
    driver.findElement(By.id("continents")).click();
    {
      WebElement dropdown = driver.findElement(By.id("continents"));
      dropdown.findElement(By.xpath("//option[. = 'Asia']")).click();
    }
    driver.findElement(By.cssSelector("#continents > option:nth-child(3)")).click();
    {
      WebElement dropdown = driver.findElement(By.id("selenium_commands"));
      dropdown.findElement(By.xpath("//option[. = 'Browser Commands']")).click();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#selenium_commands > option:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#selenium_commands > option:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#selenium_commands > option:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("#selenium_commands > option:nth-child(1)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#selenium_commands > option:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#selenium_commands > option:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("submit")).click();
  }
}
